import { createClient } from "@/lib/supabase/server";
import RetentionView, { type RetentionRow } from "./retention-view";

// Post-placement retention tracking -- the pipeline previously ended the
// moment a candidate hit stage='placed'. This surfaces the 30/90/180-day
// check-ins that get auto-generated by fn_create_retention_checkins() the
// moment date_of_joining is set on a placed link, so a recruiter has a
// working queue instead of the outcome silently never getting captured.
export default async function RetentionPage() {
  const supabase = await createClient();

  const { data, error } = await supabase
    .from("placement_retention_checkins")
    .select(
      "id, checkin_type, due_date, completed_at, outcome, notes, candidate_mandate_links(candidate_id, mandate_id, date_of_joining, candidates(full_name, current_employer), mandates(role_title, client_name))"
    )
    .order("due_date", { ascending: true });

  const rows: RetentionRow[] = (error ? [] : data ?? []).map((r) => {
    const link = r.candidate_mandate_links as unknown as {
      candidate_id: string;
      mandate_id: string;
      date_of_joining: string | null;
      candidates: { full_name: string; current_employer: string | null } | null;
      mandates: { role_title: string; client_name: string } | null;
    } | null;
    return {
      id: r.id,
      checkin_type: r.checkin_type,
      due_date: r.due_date,
      completed_at: r.completed_at,
      outcome: r.outcome,
      notes: r.notes,
      candidate_id: link?.candidate_id ?? null,
      candidate_name: link?.candidates?.full_name ?? "Unknown",
      candidate_employer: link?.candidates?.current_employer ?? null,
      role_title: link?.mandates?.role_title ?? "—",
      client_name: link?.mandates?.client_name ?? "—",
      date_of_joining: link?.date_of_joining ?? null,
    };
  });

  return (
    <div>
      <h1 className="text-xl font-semibold text-slate-900 dark:text-slate-100 mb-1">Retention check-ins</h1>
      <p className="text-sm text-slate-500 dark:text-slate-400 mb-6">
        30 / 90 / 180-day follow-ups on every placement -- generated automatically once a join date is set. This is
        the data that proves (or disproves) the retention pitch to clients, and eventually feeds back into vetting
        scores.
      </p>
      <RetentionView initialRows={rows} fetchError={error?.message ?? null} />
    </div>
  );
}
